/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.PhatThuongManagerFrame;

import controllers.PhatThuongManagerController.PhanQuaController;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.PhanQuaModel;

/**
 *
 * @author TNTDT
 */
public class ChonQuaJFrame extends javax.swing.JFrame {

    private JFrame parentJFrame;
    private  DefaultTableModel tableModel;
    private  List<PhanQuaModel> lstQua = new ArrayList<>();
    public static int idQua;

    /**
     * Creates new form ChonQuaJFrame
     */
    public ChonQuaJFrame(JFrame parentJFrame) {
        initComponents();
        this.parentJFrame = parentJFrame;
        tableModel = (DefaultTableModel) tblQua.getModel();
        tblQua.getTableHeader().setFont(new Font("Arial", Font.BOLD, 14));
        tblQua.setRowHeight(28);
        tblQua.validate();
        tblQua.repaint();
        tblQua.setFont(new Font("Arial", Font.PLAIN, 14));
        tblQua.getColumnModel().getColumn(0).setMaxWidth(40);
        tblQua.getColumnModel().getColumn(0).setMinWidth(40);
        tblQua.getColumnModel().getColumn(0).setPreferredWidth(80);

        parentJFrame.setEnabled(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parentJFrame.setEnabled(true);
                close();
            }
        });
        showQua();

    }

    public static int getIdQua() {
        return idQua;
    }

    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }

    private String chonQua() {
        int selectIndex = tblQua.getSelectedRow();
        String tenQua = "";
        if (selectIndex >= 0) {
            PhanQuaModel qua = lstQua.get(selectIndex);
            tenQua = qua.getTenQua();
            idQua = qua.getID();
        }
        return tenQua;
    }

    private void showQua() {
        lstQua = PhanQuaController.findAll();

        tableModel.setRowCount(0);
        lstQua.forEach((PhanQuaModel qua) -> {
            tableModel.addRow(new Object[]{tableModel.getRowCount() + 1, qua.getTenQua(),
                qua.getGiaTri(), qua.getSoLuong() - qua.getSoLuongDaPhat()});
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblQua = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnChon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtQuaDuocChon = new javax.swing.JLabel();
        txtQuaDcChon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Chọn Phần Thưởng");

        tblQua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "STT", "Tên Quà", "Giá Trị", "Số Lượng Còn Lại"
            }
        ));
        tblQua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQuaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQua);
        if (tblQua.getColumnModel().getColumnCount() > 0) {
            tblQua.getColumnModel().getColumn(0).setMinWidth(50);
            tblQua.getColumnModel().getColumn(0).setMaxWidth(50);
            tblQua.getColumnModel().getColumn(2).setMinWidth(100);
            tblQua.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Danh Sách Phần Thưởng");

        btnChon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChon.setText("Chọn");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Phần Quà:");

        txtQuaDuocChon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtQuaDcChon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQuaDcChon, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuaDuocChon, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnChon, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChon)
                    .addComponent(jLabel2)
                    .addComponent(txtQuaDuocChon)
                    .addComponent(txtQuaDcChon))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
        if (PhanQuaController.check(idQua)) {
            JOptionPane.showMessageDialog(rootPane, "Phần quà chọn đã hết");
        } else {
            String qua = txtQuaDcChon.getText();
            if (!"".equals(qua)) {
                this.parentJFrame.setEnabled(true);
                dispose();
                PTCuoiNamJFrame.setTxtPT(qua);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Chọn phần quà");
            }
        }
    }//GEN-LAST:event_btnChonActionPerformed

    private void tblQuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQuaMouseClicked
        // TODO add your handling code here:
        String s = chonQua();
        if (!"".equals(s)) {
            txtQuaDcChon.setText(s);
        }
    }//GEN-LAST:event_tblQuaMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblQua;
    private javax.swing.JLabel txtQuaDcChon;
    private javax.swing.JLabel txtQuaDuocChon;
    // End of variables declaration//GEN-END:variables
}
