/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.PhatThuongManagerFrame;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.MysqlConnection;

/**
 *
 * @author oOOo
 */
public class ThongKeQuaCuoiNam extends javax.swing.JFrame {
    private DefaultTableModel tblModel;
     private DefaultTableModel tblModel1;
      private JFrame parentJFrame;
        private JFrame parentFrame;
    /**
     * Creates new form ThongKeQuaDipDacBiet
     */
    public ThongKeQuaCuoiNam(JFrame parentJFrame) {
        initComponents();
        initTableModel();
        initTableModel1();
        this.parentJFrame = parentJFrame;
         parentJFrame.setEnabled(false);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                parentJFrame.setEnabled(true);
                close();
            }
        });
    }

    private void initTableModel(){
        String[] columnNames = new String[]{"ID hộ", "Số quà đã nhận", "Tổng giá trị"};
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(columnNames);
        tblthongke.setModel(tblModel);
    }
    
    private void initTableModel1(){
        String[] columnNames = new String[]{"ID Hộ Khẩu","ID nhân khẩu", "Tên nhân khẩu", "Phần quà", "Giá trị"};
        tblModel1 = new DefaultTableModel();
        tblModel1.setColumnIdentifiers(columnNames);
        tblchitiet.setModel(tblModel1);
    }
    
    private void close() {
        if (JOptionPane.showConfirmDialog(this, "Are you sure to close??", "Confirm", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            this.parentJFrame.setEnabled(true);
            dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblthongke = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnthongke = new javax.swing.JButton();
        btnchitiet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblchitiet = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblthongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID hộ", "Tổng số quà đã nhận", "Tổng giá trị"
            }
        ));
        jScrollPane1.setViewportView(tblthongke);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 383, 110));

        jLabel1.setText("Bảng thống kê số phần quà mỗi hộ đã nhận");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 240, 25));

        btnthongke.setText("Thống Kê");
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });
        getContentPane().add(btnthongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 120, -1));

        btnchitiet.setText("Thống Kê Chi Tiết");
        btnchitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchitietActionPerformed(evt);
            }
        });
        getContentPane().add(btnchitiet, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 130, -1));

        tblchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Hộ Khẩu", "ID nhân khẩu", "Họ Tên", "Phần quà", "Giá trị"
            }
        ));
        jScrollPane2.setViewportView(tblchitiet);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 200));

        jLabel2.setText("ID hộ khẩu cần thống kê");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 140, 30));
        getContentPane().add(txtTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 200, 30));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchitietActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        Statement stm = null;

          try{
            conn = MysqlConnection.getMysqlConnection();
            if(txtTimkiem.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ban chua nhap gia tri tim kiem");
            }
            else{
            String sql1 = "select t.idHoKhau, p.IDHS, n.hoTen, pt.tenphanthuong, pt.giatri from thanh_vien_cua_ho t,nhan_khau n, phat_thuong_cuoi_nam p,phan_thuong pt where t.idNhanKhau = p.IDHS and t.idNhanKhau = n.ID and p.IDPhanQua = pt.IDphanthuong and idHoKhau = "+txtTimkiem.getText()+"";
            
            PreparedStatement pstmt = conn.prepareStatement(sql1);
           
            ResultSet rs1 = pstmt.executeQuery();
            
          
                tblModel1.setRowCount(0);
            while(rs1.next()){
                tblModel1.addRow(new Object[]{
                    rs1.getInt("idHoKhau"),
                rs1.getInt("IDHS"),
                rs1.getString("hoTen"),
                rs1.getString("tenphanthuong"),
             rs1.getInt("giatri"),
            });
            }
            
            
            tblModel1.fireTableDataChanged();
            }
        }
        
        
        catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnchitietActionPerformed

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        // TODO add your handling code here:
         Connection conn = null;
        Statement stm = null;

        try{
            conn = MysqlConnection.getMysqlConnection();
           
            String sql = "select idHoKhau, count(IDPhanQua) as sophanthuong, count(IDPhanQua)*10000 as sotienqua from nhan_khau n, thanh_vien_cua_ho t, phat_thuong_cuoi_nam p where t.idNhanKhau = n.id and n.ID = p.IDHS  group by idHoKhau";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblModel.setRowCount(0);
            while(rs.next()){
                tblModel.addRow(new Object[]{
                rs.getString("idHoKhau"),
                rs.getInt("sophanthuong"),
                rs.getInt("sotienqua"),
            });
            }
            tblModel.fireTableDataChanged();
            
            }
         catch(Exception e){
            e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
        }    
    }//GEN-LAST:event_btnthongkeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if (JOptionPane.showConfirmDialog(null, "Are you sure to close this??","Confirm",JOptionPane.YES_NO_OPTION) == 0) {
            close();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeQuaCuoiNam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeQuaCuoiNam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeQuaCuoiNam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeQuaCuoiNam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchitiet;
    private javax.swing.JButton btnthongke;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblchitiet;
    private javax.swing.JTable tblthongke;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables
}
